apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: tinyurl

  template:
    metadata:
      name: tinyurl
      labels:
        app: tinyurl

    spec:
      containers:
        - name: tinyurl
          image: tinyurl_app:v2
          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

          envFrom:
            - configMapRef:
                name: tinyurl-config

            - secretRef:
                name: tinyurl-secret

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

